"""Step 01: public API for auditable engineering claims and physical residual research."""

from __future__ import annotations

from .core.calibration import calibrate_relation, validate_relation_calibration
from .core.diagnostics import residual_diagnostics
from .core.evidence import audit_physics_library, physics_readiness_report
from .core.references import RESEARCH_REFERENCES
from .core.schema import (
    AlignedSignals,
    ApplicabilityEnvelope,
    CalibrationReport,
    EvidenceClaim,
    EvidenceMaturity,
    ExperimentPlan,
    FaultSensitivity,
    MeasurementRequirement,
    MeasurementStatus,
    ParameterSource,
    ParameterSpec,
    ParameterStabilityDiagnostics,
    PhysicsReadinessEntry,
    PhysicsRelation,
    ReferenceType,
    RelationCompute,
    RelationFit,
    RelationKind,
    RelationStatus,
    ResearchCandidate,
    ResearchReference,
    ResidualDiagnostics,
    ResidualDirection,
    ResidualFmeaEntry,
    SensorFailureMode,
    UncertaintyCategory,
    UncertaintySource,
    ValidationDiagnostics,
    ValidationEvidence,
)
from .core.uncertainty import propagate_linearized_uncertainty
from .families import (
    ALL_MACHINE_FAMILIES,
    PHYSICS_RELATIONS,
    RESEARCH_CANDIDATES,
    relations_for_family,
    research_catalog_for_family,
)
from .families.final_test import contact_resistance_mohm_for_research
from .families.wafer_saw import (
    INTERCEPT,
    RESIDUAL_SCALE,
    SLOPE,
    SPEED_HIGH,
    SPEED_LOW,
    SPEED_SPAN,
    SPINDLE_EXPERIMENT,
    SPINDLE_MEASUREMENTS,
    SPINDLE_PARAMETERS,
    SPINDLE_RELATION,
)


__all__ = (
    "ALL_MACHINE_FAMILIES",
    "AlignedSignals",
    "ApplicabilityEnvelope",
    "CalibrationReport",
    "EvidenceClaim",
    "EvidenceMaturity",
    "ExperimentPlan",
    "FaultSensitivity",
    "INTERCEPT",
    "MeasurementRequirement",
    "MeasurementStatus",
    "PHYSICS_RELATIONS",
    "ParameterSource",
    "ParameterSpec",
    "ParameterStabilityDiagnostics",
    "PhysicsReadinessEntry",
    "PhysicsRelation",
    "RESEARCH_CANDIDATES",
    "RESEARCH_REFERENCES",
    "RESIDUAL_SCALE",
    "ReferenceType",
    "RelationCompute",
    "RelationFit",
    "RelationKind",
    "RelationStatus",
    "ResearchCandidate",
    "ResearchReference",
    "ResidualDiagnostics",
    "ResidualDirection",
    "ResidualFmeaEntry",
    "SLOPE",
    "SPEED_HIGH",
    "SPEED_LOW",
    "SPEED_SPAN",
    "SPINDLE_EXPERIMENT",
    "SPINDLE_MEASUREMENTS",
    "SPINDLE_PARAMETERS",
    "SPINDLE_RELATION",
    "SensorFailureMode",
    "UncertaintyCategory",
    "UncertaintySource",
    "ValidationDiagnostics",
    "ValidationEvidence",
    "audit_physics_library",
    "calibrate_relation",
    "contact_resistance_mohm_for_research",
    "physics_readiness_report",
    "propagate_linearized_uncertainty",
    "relations_for_family",
    "research_catalog_for_family",
    "residual_diagnostics",
    "validate_relation_calibration",
)
