"""Step 01: public API for auditable engineering claims and physical residual research."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Callable, Mapping, Sequence

import numpy as np
from sklearn.linear_model import HuberRegressor

from .core.schema import (
    AlignedSignals,
    ApplicabilityEnvelope,
    CalibrationReport,
    EvidenceClaim,
    EvidenceMaturity,
    ExperimentPlan,
    FaultSensitivity,
    MeasurementRequirement,
    MeasurementStatus,
    ParameterSource,
    ParameterSpec,
    ParameterStabilityDiagnostics,
    PhysicsReadinessEntry,
    PhysicsRelation,
    ReferenceType,
    RelationCompute,
    RelationFit,
    RelationKind,
    RelationStatus,
    ResearchCandidate,
    ResearchReference,
    ResidualDiagnostics,
    ResidualDirection,
    ResidualFmeaEntry,
    SensorFailureMode,
    UncertaintyCategory,
    UncertaintySource,
    ValidationDiagnostics,
    ValidationEvidence,
)
from .core.evidence import (
    ASME_UNCERTAINTY,
    BRANCA_WEB,
    BRAUN_PREPRINT,
    BRYNJARSDOTTIR_OHAGAN,
    CONTACT_EXPERIMENT,
    COOLANT_EXPERIMENT,
    DENG_REVIEW,
    DICING_DYNAMICS,
    DICING_MONITOR_PATENT,
    DISCO_PRODUCT_LINE,
    FRANK_DING_RESIDUAL,
    ISO_CONDITION_MONITORING,
    ISO_DIAGNOSTICS,
    ISO_MEASUREMENT_MANAGEMENT,
    ISO_VIBRATION_CALIBRATION,
    ISO_VIBRATION_SCOPE,
    JCGM_MONTE_CARLO,
    JCGM_UNCERTAINTY,
    JCGM_VIM,
    KEITHLEY_LOW_LEVEL,
    KENNEDY_OHAGAN,
    KEYENCE_POWER_MONITOR,
    KEYSIGHT_LOW_RESISTANCE,
    KHAN_REVIEW,
    LASER_EXPERIMENT,
    LASER_OUTPUT_MODEL,
    LEYBOLD_LEAK,
    LIU_WAFER_PROBE,
    MAXON_CONSTANTS,
    MOLDING_MONITOR,
    MOLDING_PROCESS,
    MOLD_EXPERIMENT,
    NASA_MODEL_HANDBOOK,
    NASA_MODEL_STANDARD,
    NIST_PHM,
    NIST_ROADMAP,
    NI_SOCKET_GUIDANCE,
    PRESS_EXPERIMENT,
    RAUE_IDENTIFIABILITY,
    RESEARCH_REFERENCES,
    SINGULATION_EXPERIMENT,
    TRUMPF_CONDITION_MONITORING,
    VACUUM_EXPERIMENT,
    WEB_EXPERIMENT,
    WIRE_BOND_IMPEDANCE,
    WIRE_BOND_PIEZO,
    WIRE_EXPERIMENT,
    audit_physics_library,
    physics_readiness_report,
)
from .core.calibration import calibrate_relation, validate_relation_calibration
from .core.diagnostics import residual_diagnostics
from .core.uncertainty import propagate_linearized_uncertainty
from .families import (
    ALL_MACHINE_FAMILIES,
    PHYSICS_RELATIONS,
    RESEARCH_CANDIDATES,
    relations_for_family,
    research_catalog_for_family,
)
from .families.wafer_saw import (
    INTERCEPT,
    MINIMUM_RUNTIME_SAMPLES,
    MINIMUM_SPINDLE_FIT_SAMPLES,
    MINIMUM_SPINDLE_RELATIVE_SPEED_SPAN,
    MINIMUM_SPINDLE_SPEED_LEVELS,
    MINIMUM_SPINDLE_SPEED_SPAN_RPM,
    RESIDUAL_SCALE,
    SLOPE,
    SPEED_HIGH,
    SPEED_LOW,
    SPEED_SPAN,
    SPINDLE_EXPERIMENT,
    SPINDLE_MEASUREMENTS,
    SPINDLE_PARAMETERS,
    SPINDLE_RELATION,
)
from .families.final_test import contact_resistance_mohm_for_research
